/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.entity.Curso;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class EditaNewTela extends javax.swing.JFrame {

    /**
     * Creates new form EditaNewTela
     */
    public EditaNewTela() {
        initComponents();
        mostrarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEditar = new javax.swing.JButton();
        txtCod2 = new javax.swing.JTextField();
        txtNome3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 104, -1, -1));

        txtCod2.setText("Codigo do curso:");
        jPanel1.add(txtCod2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, -1));

        txtNome3.setText("Nome:");
        jPanel1.add(txtNome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 150));

        tblEditar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Codigo do curso", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEditar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 280, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
                        
        int linhaSelecionada = tblEditar.getSelectedRow();
        if (linhaSelecionada != -1) {

            long idCurso = (long) tblEditar.getValueAt(linhaSelecionada, 0);
        

            CursoController cursoDao = new CursoController();
            Curso curso = cursoDao.findById(idCurso);
        

            curso.setNome(txtNome3.getText());
            curso.setCodigoCurso(txtCod2.getText());
            cursoDao.update(curso);
            
            JOptionPane.showMessageDialog(this, "Curso atualizado com sucesso.");
        } else {
        
            JOptionPane.showMessageDialog(this, "Selecione um curso na tabela para editar.");
        }    
    }//GEN-LAST:event_btnEditarActionPerformed
    
    private void mostrarTabela () {
        CursoController cursoDao = new CursoController();
        List<Curso> cursos = cursoDao.findAll();
   
        DefaultTableModel tableModel = (DefaultTableModel) tblEditar.getModel();
        tableModel.setRowCount(0);

        // Adiciona os cursos à tabela
        for (Curso curso : cursos) {
            tableModel.addRow(new Object[]{
            curso.getId(),
            curso.getNome(),
            curso.getCodigoCurso(),
            curso.getAtivo()
            });
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditaNewTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditaNewTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditaNewTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditaNewTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditaNewTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEditar;
    private javax.swing.JTextField txtCod2;
    private javax.swing.JTextField txtNome3;
    // End of variables declaration//GEN-END:variables
}
